'*.{js,vue}':
  - 'eslint --fix --ignore-path .eslintignore'
  - 'prettier --write --ignore-path .eslintignore'
'*.{css,scss,html,vue}':
  - 'stylelint --fix --ignore-path .stylelintignore --allow-empty-input'
  - 'prettier --write --ignore-path .stylelintignore'
'!(*.js|*.html|*.vue|*.css|*.scss)':
  - 'prettier --write --ignore-path .prettierignore --ignore-unknown'
