# Minimal Lint-Staged Config
# Lumirelle (shabbyacc@outlook.com)

'*.{js,vue}':
  - 'eslint --cache --fix'
  - 'prettier --cache --write'
'*.{css,scss,html,vue}':
  - 'stylelint --cache --fix'
  - 'prettier --cache --write'
'!(*.js|*.html|*.vue|*.css|*.scss)':
  - 'prettier --cache --write --ignore-unknown'
