showNewVersionIcon: false
hideAfterStartup: true
randomControllerPort: true
runTimeFormat: 'hh : mm : ss'
trayOrders:
  - - icon
  - - status
    - traffic
    - text
hideTrayIcon: false
connShowProcess: true
showTrayProxyDelayIndicator: true
connMode: true
connProfile: true
connProxy: 0
latencyTimeout: .nan
fontFamily: ''
proxyOrder: 0
proxyDelayType: 1
latencyUrl: http://www.apple.com/library/test/success.html
theme: 0
mixinText: |
  # Mixin 配置（覆盖配置）
  # Author：Lyana-nullptr (shabbyacc@outlook.com)
  # Last Edit：2025-02-06
  # Note：推荐为本配置使用 LF 换行格式
  mixin:
    # 覆盖 DNS 配置
    dns:
      enable: true
      ipv6: true

      # 增强模式，推荐使用 fake-ip
      enhanced-mode: fake-ip
      # fake-ip 模式使用的地址池
      fake-ip-range: 198.18.0.1/16
      # fake-ip 排除列表，支持通配符
      # 设置了通配符的域名必须使用引号包裹
      # 通配符：
      #   - `*.` 匹配单级子域名：'*.qq.com' 匹配 a.qq.com，不匹配 qq.com
      #   - `.` 匹配多级子域名：'.qq.com' 匹配 a.qq.com 和 a.b.qq.com，不匹配 qq.com
      #   - `+.` 匹配多级子域名和自身：'+.qq.com' 匹配 a.qq.com、a.b.qq.com 和 qq.com
      fake-ip-filter:
        # Local & Internal
        - '*.lan'
        - '*.local'
        - '*.docker.internal'
        - WORKGROUP
        # Connect Test
        - '*.msftncsi.com'
        - '*.msftconnecttest.com'
        # NTP
        - 'ntp.ntsc.ac.cn'
        - '*.ntp.org.cn'
        - 'ntp.*.edu.cn'
        - 'time.*.edu.cn'
        - '+.pool.ntp.org'
        - 'ntp.*.com'
        - 'ntp1.*.com'
        - 'ntp2.*.com'
        - 'ntp3.*.com'
        - 'ntp4.*.com'
        - 'ntp5.*.com'
        - 'ntp6.*.com'
        - 'ntp7.*.com'
        - 'time.*.com'
        - 'time1.*.com'
        - 'time2.*.com'
        - 'time3.*.com'
        - 'time4.*.com'
        - 'time5.*.com'
        - 'time6.*.com'
        - 'time7.*.com'
        # Social Media
        - localhost.ptlogin2.qq.com
        # Music
        - '*.y.qq.com'
        - '*.music.tc.qq.com'
        - aqqmusic.tc.qq.com
        - '*.stream.qqmusic.qq.com'
        - '*.music.163.com'
        - '*.126.net'
        - songsearch.kugou.com
        - trackercdn.kugou.com
        - '*.kuwo.cn'
        - musicapi.taihe.com
        - music.taihe.com
        # Game
        - 'xbox.*.*.microsoft.com'
        - '*.*.xboxlive.com'
        - '*.n.n.srv.nintendo.net'
        - '*.stun.playstation.net'
        # STUN Server
        - '+.stun.*.*'
        - '+.stun.*.*.*'
        - '+.stun.*.*.*.*'
        - '+.stun.*.*.*.*.*'
        - '+.stun01.*.*'
        - 'stunserver.*'
        - 'stunserver.*.*'

      # default-nameserver 用于解析 nameserver 和 fallback 中的 DNS 服务器
      # 因此必须指定 IP，支持 UDP、TCP、DoT、DoH
      # Clash 总是使用第一个结果，适当设置几个响应快的 DNS 服务器即可
      # default-nameserver:
      #   - '223.5.5.5' # 阿里 IPv4
      #   - '119.29.29.29' # 腾讯 IPv4
      #   - '[2400:3200::1]:53' # 阿里 IPv6
      #   - '[2402:4e00::]:53' # 腾讯 IPv6
      # nameserver 支持 UDP、TCP、DoT、DoH
      nameserver:
        - '223.5.5.5' # 阿里 IPv4
        - '119.29.29.29' # 腾讯 IPv4
        - '[2400:3200::1]:53' # 阿里 IPv6
        - '[2402:4e00::]:53' # 腾讯 IPv6
      # fallback 可以指定 IP 或域名，同样支持 UDP、TCP、DoT、DoH
      # 配置 fallback 后默认启用 fallback-filter, geoip-code 默认为 CN
      fallback:
        - https://223.5.5.5/dns-query # 阿里 DoH, ECS Support
        - https://1.1.1.1/dns-query # Cloudflare DoH
        - https://8.8.8.8/dns-query # Google DoH
        - tls://223.5.5.5:853 # 阿里 DoT, ECS Support
        - tls://1.1.1.1:853 # Cloudflare DoT
        - tls://8.8.8.8:853 # Google DoT
      # fallback-filter 会对 IP 进行过滤，是对抗 DNS 污染攻击的一种措施
      # 1. 当 geoip 开启且 code 设置为 CN 时
      # 属于中国的 IP 将使用 nameserver 中的 dns
      # 其它国家的 IP 将使用 fallback 中的 dns
      # 2. 当请求的域名匹配 domain 且 dns 响应的 ip 匹配 ip-cidr 时
      # 强制使用 fallback 中的 dns
      fallback-filter:
        geoip: true
        geoip-code: CN
        ip-cidr:
          - 240.0.0.0/4
        domain:
          - '+.google.com'
          - '+.facebook.com'
          - '+.twitter.com'
          - '+.youtube.com'
          - '+.xn--ngstr-lra8j.com'
          - '+.google.cn'
          - '+.googleapis.cn'
          - '+.googleapis.com'
          - '+.gvt1.com'

    # 覆盖 Tun 配置
    tun:
      # TUN 设备可以用来处理 TCP、UDP、ICMP 流量，将流量转发到虚拟网卡，实现代理
      # 需要在 `General -> Service Mode` 安装服务
      enable: true
      # 推荐使用 system，需要在 `General -> Clash Core` 添加防火墙规则
      stack: system
      # 当 fake-ip-range 是 198.18.0.1/16, 应该劫持 198.18.0.2:53，请勿修改
      dns-hijack:
        - 198.18.0.2:53
      # 自动管理系统路由表，实现代理，仅接收 IPv4 流量
      auto-route: true
      # 更推荐使用 interface-name 指定网卡名称
      auto-detect-interface: true
    # interface-name: 'tun0'
profileParsersText: >
  # Parsers 配置，Profile 处理器，支持设置多个（数组格式）

  # Author: Lyana-nullptr

  # Last Edit: 2025-02-06

  # Note：推荐为本配置使用 LF 换行格式

  parsers:
    # - reg: ^.*$ 匹配所有订阅
    # - url: https://example.com/profile.yaml 匹配指定订阅
    - reg: ^.*$
      # 删除服务商提供的 DNS、策略组、规则提供者和规则
      code: |
        module.exports.parse = (raw, { yaml }) => {
          const rawObj = yaml.parse(raw)
          return yaml.stringify({
            ...rawObj,
            dns: {},
            'proxy-groups': [],
            'rule-providers': [],
            rules: []
          })
        }
      # 插入自己的配置
      yaml:
        # 插入策略组
        # 策略组示例
        # - name: 策略组名
        #   type: select / url-test / fallback / load-balance     # 手动选择/延迟测试/回退/负载均衡
        #   url: http://www.apple.com/library/test/success.html   # 测试地址
        #   interval: 60                                          # 测试间隔（s）
        #   tolerance: 150                                        # 容忍度（ms）
        #   proxies:
        #       - 节点名称
        #       - 其他分组的套娃
        prepend-proxy-groups:
          - name: 👾 去魔法世界
            type: select
            proxies:
              - 🧭 就近原则
              - 🚢 想去祖国的小岛
              - ⚓ 想去华人步行街
              - ⛩️ 想去岛国还人情
              - 🔫 想去自由美利坚
              - 🤣 你选的嘛偶像
          - name: 🧭 就近原则
            type: url-test
            url: http://www.apple.com/library/test/success.html
            interval: 60
            tolerance: 150
          - name: 🚢 想去祖国的小岛
            type: url-test
            url: http://www.apple.com/library/test/success.html
            interval: 180
            tolerance: 150
          - name: ⚓ 想去华人步行街
            type: url-test
            url: http://www.apple.com/library/test/success.html
            interval: 180
            tolerance: 150
          - name: ⛩️ 想去岛国还人情
            type: url-test
            url: http://www.apple.com/library/test/success.html
            interval: 180
            tolerance: 150
          - name: 🔫 想去自由美利坚
            type: url-test
            url: http://www.apple.com/library/test/success.html
            interval: 180
            tolerance: 150
          - name: 🤣 你选的嘛偶像
            type: select
          - name: 👻 鬼屋
            type: select
            proxies:
              - REJECT
              - DIRECT
          - name: 🦓 迷路了怎么斑马
            type: select
            proxies:
              - 👾 去魔法世界
              - DIRECT
        # 用命令预处理策略组
        commands:
          # 一些可能用到的正则过滤节点示例，使分组更细致
          # []proxyNames|a                         # 包含a
          # []proxyNames|^(.*)(a|b)+(.*)$          # 包含a或b
          # []proxyNames|^(?=.*a)(?=.*b).*$        # 包含a和b
          # []proxyNames|^((?!b).)*a((?!b).)*$     # 包含a且不包含b
          # []proxyNames|^((?!b|c).)*a((?!b|c).)*$ # 包含a且不包含b或c
          # 向指定策略组添加订阅中符合地区的节点
          - proxy-groups.🧭 就近原则.proxies.0+[]proxyNames
          - proxy-groups.🚢 想去祖国的小岛.proxies.0+[]proxyNames|^(.*)(香港|澳门|台湾)+(.*)$
          - proxy-groups.⚓ 想去华人步行街.proxies.0+[]proxyNames|新加坡
          - proxy-groups.⛩️ 想去岛国还人情.proxies.0+[]proxyNames|日本
          - proxy-groups.🔫 想去自由美利坚.proxies.0+[]proxyNames|美国
          - proxy-groups.🤣 你选的嘛偶像.proxies.0+[]proxyNames

        # 插入规则提供者
        # 国内环境推荐使用 https://gcore.jsdelivr.net/ CDN 加速 GitHub 资源
        mix-rule-providers:
          applications:
            type: http
            behavior: classical
            url: 'https://gcore.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/applications.txt'
            path: ./ruleset/applications.yaml
            interval: 86400
          private:
            type: http
            behavior: domain
            url: 'https://gcore.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/private.txt'
            path: ./ruleset/private.yaml
            interval: 86400
          reject:
            type: http
            behavior: domain
            url: 'https://gcore.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/reject.txt'
            path: ./ruleset/reject.yaml
            interval: 86400
          icloud:
            type: http
            behavior: domain
            url: 'https://gcore.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/icloud.txt'
            path: ./ruleset/icloud.yaml
            interval: 86400
          apple:
            type: http
            behavior: domain
            url: 'https://gcore.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/apple.txt'
            path: ./ruleset/apple.yaml
            interval: 86400
          google:
            type: http
            behavior: domain
            url: 'https://gcore.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/google.txt'
            path: ./ruleset/google.yaml
            interval: 86400
          proxy:
            type: http
            behavior: domain
            url: 'https://gcore.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/proxy.txt'
            path: ./ruleset/proxy.yaml
            interval: 86400
          direct:
            type: http
            behavior: domain
            url: 'https://gcore.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/direct.txt'
            path: ./ruleset/direct.yaml
            interval: 86400
          lancidr:
            type: http
            behavior: ipcidr
            url: 'https://gcore.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/lancidr.txt'
            path: ./ruleset/lancidr.yaml
            interval: 86400
          cncidr:
            type: http
            behavior: ipcidr
            url: 'https://gcore.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/cncidr.txt'
            path: ./ruleset/cncidr.yaml
            interval: 86400
          telegramcidr:
            type: http
            behavior: ipcidr
            url: 'https://gcore.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/telegramcidr.txt'
            path: ./ruleset/telegramcidr.yaml
            interval: 86400

        # 插入规则
        # 规则由上往下匹配，即：上面规则命中就不再往下匹配
        prepend-rules:
          # 在这里添加自己的规则
          # Connect Test
          - DOMAIN,www.msftconnecttest.com,👾 去魔法世界
          - DOMAIN,www.msftncsi.com,👾 去魔法世界
          # 订阅服务
          - DOMAIN,cm-sub.pz.pe,DIRECT
          # 游戏联机
          - PROCESS-NAME,ForzaHorizon4.exe,DIRECT
          # Steam 下载服务直连，省流量
          - DOMAIN-SUFFIX,cm.steampowered.com,DIRECT
          - DOMAIN-SUFFIX,steamserver.net,DIRECT
          # 其他
          - DOMAIN-SUFFIX,tampermonkey.net,👾 去魔法世界

          # Provider 推荐的匹配规则
          - RULE-SET,applications,DIRECT # 需要直连的进程/应用
          - RULE-SET,private,DIRECT # 需要直连的私有域名
          - RULE-SET,reject,👻 鬼屋 # 拦截域名
          - RULE-SET,icloud,DIRECT # iCloud
          - RULE-SET,apple,DIRECT # Apple
          - RULE-SET,google,PROXY # Google
          - RULE-SET,proxy,👾 去魔法世界 # 需要代理的域名
          - RULE-SET,direct,DIRECT # 需要直连的域名
          - RULE-SET,lancidr,DIRECT # 本地 IP 池
          - RULE-SET,cncidr,DIRECT # 国内 IP 池
          - RULE-SET,telegramcidr,👾 去魔法世界 # Telegram IP 池
          - GEOIP,LAN,DIRECT
          - GEOIP,CN,DIRECT
          - MATCH,🦓 迷路了怎么斑马
editor: 1
editorFontSize: 14
showNotifications: false
titleBarText: 'Current Mode: %mode%, Mixin Status: %mixin%. (,,´•ω•)ノ"(´っω•｀。)'
trayProxiesStyle: 1
hideUnselectableGroup: true
showProxyFilter: true
connChainType: 2
checkForUpdates: false
childProcessText: |
  processes: # array
systemTheme: true
useModeIcons: true
