catalogs:
  dev:
    '@antfu/eslint-config': ^4.12.0
    '@types/node': ^22.15.3
    bumpp: ^10.1.0
    eslint: ^9.25.1
    eslint-plugin-format: ^1.0.1
    lint-staged: ^15.5.1
    simple-git-hooks: ^2.12.1
    taze: ^19.0.4
    tinyglobby: ^0.2.13
    tsx: ^4.19.3
    typescript: ^5.8.3
    unbuild: ^3.5.0
    vitest: ^3.1.2
  prod:
    ansis: ^3.17.0
  prod-inlined:
    '@posva/prompts': ^2.4.4
