catalogs:
  dev:
    '@antfu/eslint-config': ^4.13.2
    '@prettier/plugin-xml': ^3.4.1
    '@types/node': ^22.15.21
    bumpp: ^10.1.1
    eslint: ^9.27.0
    eslint-plugin-format: ^1.0.1
    hint: ^7.1.13
    lint-staged: ^15.5.2
    simple-git-hooks: ^2.13.0
    taze: ^19.1.0
    tsx: ^4.19.4
    typescript: ^5.8.3
    unbuild: ^3.5.0
    vitest: ^3.1.4
  prod:
    ansis: ^4.0.0
    tinyglobby: ^0.2.13
  prod-inlined:
    '@posva/prompts': ^2.4.4
