# NOTE: Docker Compose 通常用于管理持久层容器，例如：MySQL、Redis、MongoDB 等
version: '3.9'

services:
  # ！MySQL 容器配置
  mysql:
    image: mysql:lts
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: database
      TZ: Asia/Shanghai
    ports:
      - 3306:3306
    volumes:
      # - mysql_data:/var/lib/mysql
      - ./data/mysql:/var/lib/mysql
    networks:
      - backend

  # ！Redis 容器配置
  redis:
    image: redis:latest
    # command: --requirepass "12345678"  # Uncomment if you need a password
    environment:
      TZ: Asia/Shanghai
    ports:
      - 6379:6379
    volumes:
      # - redis_data:/data
      - ./data/redis:/data
    networks:
      - backend

# 卷配置，如果使用了卷，需要允许外部访问
volumes:
  mysql-data:
    driver: local
  redis-data:
    driver: local

# 网络配置
networks:
  backend:
    driver: bridge
